// <auto-generated />
namespace QuizAdmin.Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DT_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DT_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201806082022215_DT_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
